package amf.core.internal.annotations
import amf.core.client.scala.model.domain._

case class AutoGeneratedName() extends SerializableAnnotation with PerpetualAnnotation {
  override val name: String  = "auto-generated-name"
  override val value: String = ""
}

object AutoGeneratedName extends AnnotationGraphLoader {
  override def unparse(value: String, objects: Map[String, AmfElement]): Option[Annotation] =
    Some(AutoGeneratedName())
}
