package amf.core.internal.remote

/**
  *
  */
object Mimes {
  val `text/yaml`: String                 = "text/yaml"
  val `text/x-yaml`: String               = "text/x-yaml"
  val `text/vnd.yaml`: String             = "text/vnd.yaml"
  val `text/json`: String                 = "text/json"
  val `application/refs+json`: String     = "application/refs+json"
  val `application/json`: String          = "application/json"
  val `application/refs+yaml`: String     = "application/refs+yaml"
  val `application/yaml`: String          = "application/yaml"
  val `application/xml`: String           = "application/xml"
  val `application/x-yaml`: String        = "application/x-yaml"
  val `application/raml+yaml`: String     = "application/raml+yaml"
  val `application/raml+json`: String     = "application/raml+json"
  val `application/raml`: String          = "application/raml"
  val `application/openapi+json`: String  = "application/openapi+json"
  val `application/swagger+json`: String  = "application/swagger+json"
  val `application/openapi+yaml`: String  = "application/openapi+yaml"
  val `application/swagger+yaml`: String  = "application/swagger+yaml"
  val `application/openapi`: String       = "application/openapi"
  val `application/swagger`: String       = "application/swagger"
  val `application/asyncapi+json`: String = "application/asyncapi+json"
  val `application/async+json`: String    = "application/async+json"
  val `application/asyncapi+yaml`: String = "application/asyncapi+yaml"
  val `application/async+yaml`: String    = "application/async+yaml"
  val `application/asyncapi`: String      = "application/asyncapi"
  val `application/async`: String         = "application/async"
  val `application/ld+json`: String       = "application/ld+json"
  val `application/amf+json`: String      = "application/amf+json"
  val `application/graph`: String         = "application/graph"
  val `text/n3`: String                   = "text/n3"
  val `text/rdf+n3`: String               = "text/rdf+n3"
  val `application/x-turtle`              = "application/x-turtle"
  val `text/turtle`                       = "text/turtle"
  val `text/plain`                        = "text/plain"
  val `application/rdf+xml`               = "application/rdf+xml"
  val `application/aml+yaml`: String      = "application/aml+yaml"
  val `application/aml+json`: String      = "application/aml+json"
  val `application/aml`: String           = "application/aml"
}
