addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"  % "1.1.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"               % "1.7.0")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"             % "1.6.1")
addSbtPlugin("org.scalastyle"     %% "scalastyle-sbt-plugin"    % "1.0.0")
addSbtPlugin("com.sonar-scala"    % "sbt-sonar"                 % "2.3.0")
addSbtPlugin("com.eed3si9n"       % "sbt-sriracha"              % "0.1.0")
addSbtPlugin("com.github.cb372"   % "sbt-explicit-dependencies" % "0.2.16")
