package amf.core.client.common.parser

import amf.core.internal.convert.NativeOpsFromJvm

class JvmAmfEmbeddedGraphParserTest extends EmbeddedGraphParserTest with NativeOpsFromJvm

class JvmAmfFlattenedGraphParserTest extends FlattenedGraphParserTest with NativeOpsFromJvm
